services:
  odoo:
    image: odoo-17-ec-dlt
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/opt/odoo/config/odoo.conf
    environment:
      - HOST=db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=security001
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
